import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Rubik } from "next/font/google";

import "./globals.css";
import ConditionalNavbar from "../components/ConditionalNavbar"; // baru

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-rubik",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-rubik ${geistSans.variable} ${geistMono.variable} ${rubik.variable} antialiased flex flex-col min-h-screen`}
      >
<<<<<<< HEAD
        <header className="fixed top-0 left-0 right-0 py-15 h-15 text-black flex px-4 items-center justify-center">
          <div className="bg-white/20 backdrop-blur-sm border border-white/30 rounded-3xl max-w-7xl w-full flex items-center justify-between px-8 py-2">
            <Link href="./" className="flex items-center gap-x-2">
              <Image
                src="/logo-transparent.png"
                alt="Logo"
                width={80}
                height={80}
              />
            </Link>
            <div className="flex gap-x-8 justify-center font-bold text-gray-900 hover:text-gray-900">
              <Link href="./" className="hover:text-blue-600 transition-colors">
                Home
              </Link>
              <Link
                href="./dashboard"
                className="hover:text-blue-600 transition-colors"
              >
                Dashboard
              </Link>
              <Link
                href="./Features"
                className="hover:text-blue-600 transition-colors"
              >
                Features
              </Link>
              <Link
                href="./community"
                className="hover:text-blue-600 transition-colors"
              >
                Community
              </Link>
              <Link
                href="./about"
                className="hover:text-blue-600 transition-colors"
              >
                About
              </Link>
            </div>
            <Link
              href="./sign-in"
              className="bg-gradient-to-r from-blue-500 to-purple-600 hover:from-blue-600 hover:to-purple-700 text-white font-semibold py-2 px-6 rounded-2xl transition-all duration-300 shadow-lg hover:shadow-xl transform hover:scale-105"
            >
              Get Started
            </Link>
          </div>
        </header>

        <main className="flex-1 pt-15">{children}</main>

        {/* footer */}
        <footer className="text-black w-full px-4 py-4">
          <div className="border border-white rounded-2xl bg-white/10 max-w-6xl mx-auto py-4 flex items-center justify-between">
            <p className="text-sm">© 2025 Your Company</p>
            <div className="flex gap-x-4"></div>
          </div>
        </footer>
=======
        <ConditionalNavbar />
        <main className="flex-1">{children}</main>
>>>>>>> fitur-dashboard
      </body>
    </html>
  );
}
